spring:
  application:
    name: devbank

  datasource:
    url: jdbc:postgresql://localhost:5432/devbank
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080